quarkus.http.port=8085

quarkus.log.level=INFO
quarkus.http.limits.max-form-attribute-size=4096

quarkus.mongodb.connection-string = ${MONGODB-CONNECTION-STRING}
quarkus.mongodb.database = selcMsCore

institution-cdc.table.name=${START_AT_TABLE_NAME:CdCStartAt}
institution-cdc.storage.connection-string=${STORAGE_CONNECTION_STRING:UseDevelopmentStorage=true;}

institution-cdc.servicebus.connection-string=Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
institution-cdc.servicebus.topic=institutionTopic
