name: Deploy SELC - institution-send-mail-scheduler

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "apps/institution-send-mail-scheduler/**"
      - "infra/container_apps/institution-send-mail-scheduler/**"
      - "apps/pom.xml"
      - "pom.xml"
  
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Dev] Institution send mail scheduler Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev
      dir: 'infra/container_apps/institution-send-mail-scheduler'
      dockerfile_path: ./apps/institution-send-mail-scheduler/Dockerfile
      docker_image_name: pagopa/selfcare-institution-send-mail-scheduler
      upload_openapi_enabled: false

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[UAT] Institution send mail scheduler Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat
      dir: 'infra/container_apps/institution-send-mail-scheduler'
      dockerfile_path: ./apps/institution-send-mail-scheduler/Dockerfile
      docker_image_name: pagopa/selfcare-institution-send-mail-scheduler
      upload_openapi_enabled: false

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Prod] Institution send mail scheduler Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod
      dir: 'infra/container_apps/institution-send-mail-scheduler'
      dockerfile_path: ./apps/institution-send-mail-scheduler/Dockerfile
      docker_image_name: pagopa/selfcare-institution-send-mail-scheduler
      upload_openapi_enabled: false
