name: Release - institution-ms

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - "apps/institution-ms/**"
      - "infra/container_apps/institution-ms/**"
      - "apps/pom.xml"
      - "pom.xml"

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Dev] Institution Ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev
      dir: 'infra/container_apps/container_apps'
      dockerfile_path: ./apps/institution-ms/Dockerfile
      docker_image_name: pagopa/institution-ms
      upload_openapi_enabled: false

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[UAT] Core ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat
      dir: 'infra/container_apps/container_apps'
      dockerfile_path: ./apps/institution-ms/Dockerfile
      docker_image_name: pagopa/institution-ms
      upload_openapi_enabled: false

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Prod] Core ms Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod
      dir: 'infra/container_apps/container_apps'
      dockerfile_path: ./apps/institution-ms/Dockerfile
      docker_image_name: pagopa/institution-ms
      upload_openapi_enabled: false

  promote_release:
    name: 'Promote prerelase release'
    runs-on: ubuntu-20.04
    needs: [release_prod]
    steps:
      - uses:  pagopa/selfcare-commons/github-actions-template/promote-release@main
        with:
          github_path_token: ${{ secrets.GH_PAT_VARIABLES }}
          release_version: ${{ vars.CURRENT_UAT_VERSION }}